-- 031_sub_agents.sql
-- Sub-agent portal for travel agencies. Main agency creates sub-agents who sell packages.
-- Auto-generates najava + ugovor + faktura when a sale is created.

CREATE TABLE IF NOT EXISTS sub_agents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    commission_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sub_agent_sales (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    sub_agent_id UUID NOT NULL REFERENCES sub_agents(id) ON DELETE CASCADE,
    reservation_id UUID NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    commission_amount NUMERIC(12,2) NOT NULL,
    documents_generated JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sub_agents_org ON sub_agents(org_id, name);
CREATE INDEX IF NOT EXISTS idx_sub_agents_org_active ON sub_agents(org_id, is_active DESC);
CREATE INDEX IF NOT EXISTS idx_sub_agent_sales_reservation ON sub_agent_sales(reservation_id);
CREATE INDEX IF NOT EXISTS idx_sub_agent_sales_org ON sub_agent_sales(org_id, created_at DESC);

ALTER TABLE sub_agents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant access - Sub agents" ON sub_agents;
CREATE POLICY "Tenant access - Sub agents" ON sub_agents
    FOR ALL USING (org_id = get_my_org_id()) WITH CHECK (org_id = get_my_org_id());

ALTER TABLE sub_agent_sales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tenant access - Sub agent sales" ON sub_agent_sales;
CREATE POLICY "Tenant access - Sub agent sales" ON sub_agent_sales
    FOR ALL USING (org_id = get_my_org_id()) WITH CHECK (org_id = get_my_org_id());

COMMENT ON TABLE sub_agents IS 'Travel agency sub-agents who sell packages';
COMMENT ON COLUMN sub_agents.commission_rate IS 'Commission percentage (e.g. 5.0 = 5%)';
COMMENT ON TABLE sub_agent_sales IS 'Records of sales generated by sub-agents';
COMMENT ON COLUMN sub_agent_sales.documents_generated IS 'JSON array of document types pre-generated: [{type:"najava",url},{type:"ugovor",url},{type:"faktura",url}]';
