import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router';
import PageMeta from '../components/common/PageMeta';
import Badge from '../components/ui/badge/Badge';
import Button from '../components/ui/button/Button';
import Input from '../components/form/input/InputField';
import Label from '../components/form/Label';
import EmptyState from '../components/ui/EmptyState';
import { useToast } from '../context/ToastContext';
import { useT } from '../lib/i18n/context';
import { createItineraryItem, createItineraryVersion, deleteItineraryItem, getItinerary, updateItineraryItem, type CreateItineraryItem, type Itinerary } from '../api/itineraries';
import { getSuppliers, type SupplierService } from '../api/suppliers';

const emptyItem: CreateItineraryItem = { dayNumber: 1, sortOrder: 0, quantity: 1, included: true, supplierServiceId: null, title: '', startTime: null, description: null, location: null, category: 'other', unit: 'fixed', netUnitPrice: 0, currency: 'BAM', markupPercent: 0 };

export default function ItineraryDetail() {
  const { id = '' } = useParams(); const { t } = useT(); const c = t.itineraries; const { success, error: showError } = useToast();
  const [data, setData] = useState<Itinerary | null>(null); const [services, setServices] = useState<(SupplierService & { supplierName: string })[]>([]);
  const [loading, setLoading] = useState(true); const [itemOpen, setItemOpen] = useState(false); const [saving, setSaving] = useState(false); const [item, setItem] = useState<CreateItineraryItem>(emptyItem);
  const [editingId, setEditingId] = useState<string | null>(null); const [editItem, setEditItem] = useState<CreateItineraryItem>(emptyItem);
  const load = async () => { setLoading(true); try { setData(await getItinerary(id)); } catch (e: any) { showError(e?.message || c.loadError); } finally { setLoading(false); } };
  useEffect(() => {
    void load();
    void getSuppliers({ status: 'active' }).then((rows) => {
      setServices(rows.flatMap((supplier) => supplier.services
        .filter((service) => service.active)
        .map((service) => ({ ...service, supplierName: supplier.name }))));
    });
  }, [id]);
  const current = data?.versions.find((version) => version.versionNumber === data.currentVersion); const items = current?.items || [];
  const days = useMemo(() => { const max = Math.max(1, ...items.map((row) => row.dayNumber)); return Array.from({ length: max }, (_, index) => index + 1); }, [items]);
  const netByCurrency = useMemo(() => items.reduce<Record<string, number>>((acc, row) => { acc[row.currency] = (acc[row.currency] || 0) + row.netUnitPrice * row.quantity; return acc; }, {}), [items]);
  const addItem = async () => { if (!item.supplierServiceId && !item.title?.trim()) return showError(c.itemTitleRequired); setSaving(true); try { await createItineraryItem(id, { ...item, dayNumber: Number(item.dayNumber), quantity: Number(item.quantity), netUnitPrice: Number(item.netUnitPrice || 0), markupPercent: Number(item.markupPercent || 0) }); success(c.itemSaved); setItemOpen(false); setItem({ ...emptyItem, dayNumber: item.dayNumber, currency: data?.currency || 'BAM' }); await load(); } catch (e: any) { showError(e?.message || c.saveError); } finally { setSaving(false); } };
  const clone = async () => { if (!data) return; setSaving(true); try { await createItineraryVersion(id, `${c.version} ${data.currentVersion + 1}`); success(c.versionCreated); await load(); } catch (e: any) { showError(e?.message || c.saveError); } finally { setSaving(false); } };
  const startEdit = (row: any) => { setEditingId(row.id); setEditItem({ dayNumber: row.dayNumber, sortOrder: row.sortOrder, quantity: row.quantity, included: row.included, startTime: row.startTime, title: row.title, description: row.description, location: row.location, category: row.category, supplierServiceId: row.supplierServiceId, unit: row.unit, netUnitPrice: row.netUnitPrice, currency: row.currency, markupPercent: row.markupPercent }); };
  const saveEdit = async () => { if (!editingId) return; setSaving(true); try { await updateItineraryItem(editingId, { quantity: Number(editItem.quantity), netUnitPrice: Number(editItem.netUnitPrice || 0), markupPercent: Number(editItem.markupPercent || 0), title: editItem.title, description: editItem.description, dayNumber: Number(editItem.dayNumber), startTime: editItem.startTime || null, location: editItem.location || null, category: editItem.category, included: editItem.included }); success(c.itemUpdated); setEditingId(null); await load(); } catch (e: any) { showError(e?.message || c.saveError); } finally { setSaving(false); } };
  const remove = async (itemId: string) => { try { await deleteItineraryItem(itemId); success(c.itemRemoved); await load(); } catch (e: any) { showError(e?.message || c.saveError); } };
  if (loading) return <div className="h-[600px] animate-pulse rounded-xl bg-gray-100 dark:bg-white/[0.04]" />;
  if (!data) return <EmptyState title={c.notFound} description={c.notFoundDescription} />;
  return <>
    <PageMeta title={`${data.title} | Travline`} description={c.workspaceDescription} />
    <div className="mb-5"><Link to="/itineraries" className="text-sm font-medium text-brand-600 hover:text-brand-700 dark:text-brand-400">← {c.back}</Link></div>
    <header className="mb-6 flex flex-col gap-4 border-b border-gray-200 pb-5 sm:flex-row sm:items-start sm:justify-between dark:border-gray-800"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-gray-900 dark:text-white">{data.title}</h1><Badge size="sm" color={data.status === 'active' ? 'success' : 'light'}>{c.statuses[data.status]}</Badge><Badge size="sm" color="primary">v{data.currentVersion}</Badge></div><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{data.destination || c.noDestination} · {data.travelers} {c.travelers}{data.inquiry ? ` · ${c.inquiry}: ${data.inquiry.contactName}` : ''}</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void clone()} disabled={saving}>{c.newVersion}</Button><Button onClick={() => { setItem({ ...emptyItem, dayNumber: days.length, currency: data.currency }); setItemOpen(true); }}>{c.addItem}</Button></div></header>
    <div className="mb-6 flex flex-wrap gap-3">{Object.entries(netByCurrency).map(([currency, value]) => <div key={currency} className="rounded-lg border border-gray-200 bg-white px-4 py-3 dark:border-gray-800 dark:bg-gray-900"><p className="text-xs text-gray-500 dark:text-gray-400">{c.netSnapshot}</p><p className="mt-0.5 text-lg font-semibold tabular-nums text-gray-900 dark:text-white">{value.toLocaleString()} {currency}</p></div>)}<div className="rounded-lg border border-dashed border-gray-300 px-4 py-3 dark:border-gray-700"><p className="text-xs text-gray-500 dark:text-gray-400">{c.versionHistory}</p><p className="mt-0.5 text-sm font-semibold text-gray-900 dark:text-white">{data.versions.map((v) => `v${v.versionNumber}`).join(' · ')}</p></div></div>
    {editingId && <section className="mb-6 rounded-xl border border-brand-200 bg-brand-50/50 p-5 dark:border-brand-500/20 dark:bg-brand-500/[0.05]"><div className="mb-4 flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold text-gray-900 dark:text-white">{c.editItem || 'Edit Item'}</h2></div><button onClick={() => setEditingId(null)} className="text-sm font-medium text-gray-500 hover:text-gray-900 dark:hover:text-white">{c.close}</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Field label={c.supplierService}><Select value={editItem.supplierServiceId || ''} onChange={(v) => setEditItem({ ...editItem, supplierServiceId: v || null })} options={[{ value: '', label: c.manualItem }, ...services.map((s) => ({ value: s.id, label: `${s.supplierName} — ${s.name} (${s.netPrice} ${s.currency})` }))]} /></Field><Field label={c.manualTitle}><Input value={editItem.title || ''} onChange={(e) => setEditItem({ ...editItem, title: e.target.value })} /></Field><Field label={c.day}><Input type="number" min="1" value={editItem.dayNumber} onChange={(e) => setEditItem({ ...editItem, dayNumber: Number(e.target.value) })} /></Field><Field label={c.time}><Input type="time" value={editItem.startTime || ''} onChange={(e) => setEditItem({ ...editItem, startTime: e.target.value || null })} /></Field><Field label={c.quantity}><Input type="number" min="0.01" step={0.01} value={editItem.quantity} onChange={(e) => setEditItem({ ...editItem, quantity: Number(e.target.value) })} /></Field><Field label={c.location}><Input value={editItem.location || ''} onChange={(e) => setEditItem({ ...editItem, location: e.target.value || null })} /></Field><div className="flex items-end justify-end gap-2 sm:col-span-2"><Button variant="outline" onClick={() => setEditingId(null)}>{c.cancel}</Button><Button onClick={() => void saveEdit()} disabled={saving}>{saving ? c.saving : c.saveItem}</Button></div></div></section>}
    {itemOpen && <section className="mb-6 rounded-xl border border-brand-200 bg-brand-50/50 p-5 dark:border-brand-500/20 dark:bg-brand-500/[0.05]"><div className="mb-4 flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold text-gray-900 dark:text-white">{c.addItem}</h2><p className="mt-1 text-xs leading-5 text-gray-500 dark:text-gray-400">{c.addItemDescription}</p></div><button onClick={() => setItemOpen(false)} className="text-sm font-medium text-gray-500 hover:text-gray-900 dark:hover:text-white">{c.close}</button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Field label={c.supplierService}><Select value={item.supplierServiceId || ''} onChange={(v) => setItem({ ...item, supplierServiceId: v || null })} options={[{ value: '', label: c.manualItem }, ...services.map((s) => ({ value: s.id, label: `${s.supplierName} — ${s.name} (${s.netPrice} ${s.currency})` }))]} /></Field><Field label={c.manualTitle}><Input value={item.title || ''} onChange={(e) => setItem({ ...item, title: e.target.value })} /></Field><Field label={c.day}><Input type="number" min="1" value={item.dayNumber} onChange={(e) => setItem({ ...item, dayNumber: Number(e.target.value) })} /></Field><Field label={c.time}><Input type="time" value={item.startTime || ''} onChange={(e) => setItem({ ...item, startTime: e.target.value || null })} /></Field><Field label={c.quantity}><Input type="number" min="0.01" step={0.01} value={item.quantity} onChange={(e) => setItem({ ...item, quantity: Number(e.target.value) })} /></Field><Field label={c.location}><Input value={item.location || ''} onChange={(e) => setItem({ ...item, location: e.target.value || null })} /></Field><div className="flex items-end justify-end gap-2 sm:col-span-2"><Button variant="outline" onClick={() => setItemOpen(false)}>{c.cancel}</Button><Button onClick={() => void addItem()} disabled={saving}>{saving ? c.saving : c.saveItem}</Button></div></div></section>}
    {items.length === 0 ? <EmptyState title={c.noItems} description={c.noItemsDescription} action={{ label: c.addItem, onClick: () => setItemOpen(true) }} /> : <div className="space-y-5">{days.map((day) => <section key={day} className="overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900"><header className="border-b border-gray-200 bg-gray-50 px-5 py-3 dark:border-gray-800 dark:bg-white/[0.02]"><h2 className="text-sm font-semibold text-gray-900 dark:text-white">{c.day} {day}</h2></header><div>{items.filter((row) => row.dayNumber === day).map((row) => <article key={row.id} className="flex flex-col gap-3 border-b border-gray-100 px-5 py-4 last:border-0 sm:flex-row sm:items-start dark:border-gray-800"><div className="w-14 shrink-0 text-sm font-semibold tabular-nums text-brand-600 dark:text-brand-400">{row.startTime || '—'}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-gray-900 dark:text-white">{row.title}</h3><Badge size="sm" color="light">{row.category}</Badge></div>{row.location && <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">{row.location}</p>}<p className="mt-2 text-xs text-gray-500 dark:text-gray-400">{row.quantity} × {row.netUnitPrice.toLocaleString()} {row.currency} · {row.unit}</p></div><div className="flex gap-1 self-start"><button onClick={() => startEdit(row)} className="text-xs font-medium text-brand-600 hover:text-brand-700 dark:text-brand-400">{c.edit || '✎'}</button><button onClick={() => void remove(row.id)} className="text-xs font-medium text-error-600 hover:text-error-700 dark:text-error-400">{c.remove}</button></div></article>)}</div></section>)}</div>}
  </>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <div><Label>{label}</Label><div className="mt-1.5">{children}</div></div>; }
function Select({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-800 focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-500/15 dark:border-gray-700 dark:bg-gray-900 dark:text-white">{options.map((option) => <option key={option.value || 'empty'} value={option.value}>{option.label}</option>)}</select>; }
